### ISSUE TITLE
This application does not seem to work on Android 5.0

### ISSUE THREAD

**Issue by SSS1110** [jaroslavas/Gstreamer-Android-example#1]

**Comment by zella** [comment]
Prebuild tutorial from http://docs.gstreamer.com/display/GstSDK/Android+tutorial+5%3A+A+Complete+media+player also crashes on my 5.1.1 nexus 5

**Comment by jaroslavas** [comment]
Do you have any logs? Works perfectly on my S4 with 5.1.1.

**Comment by zella** [comment]
I tried precompled apk only. And in logcat i see only line:

```
com.gst_sdk_tutorials.tutorial_5 A/libc﹕ Fatal signal 11 (SIGSEGV), code 1, fault addr 0x52c in tid 5708 (multiqueue0:src)
```
