### ISSUE TITLE
General supporting library error

### ISSUE THREAD

**Issue by oradkovsky** [jaroslavas/Gstreamer-Android-example#2]
Hi. I'm getting "Error received from element amcvideodecomxmtkvideodecoderavc6: Gstreamer encountered a general supporting library error". The error is reproducible using gstreamer 1.4.4 release (arm) BUT the app works just fine if uses x86 of same version. I'm using the app to play live rtsp stream. One thing to note so: as I do not have hardware x86 mobile device, I was using emulator. So on x86 emulator - works. On armeabi emulator - not working.

**Comment by jaroslavas** [comment]
Maybe you do not include arm libs in the app?

**Comment by oradkovsky** [comment]
I did BUT you know it seems to be some memory leak issue on hardware device. After reboot it started working without changes. So thank you for your attention and thank you for great app sample - it was very useful to make these things work!
