### ISSUE TITLE
Issue with the dependent library

### ISSUE THREAD

**Issue by konstantin-doncov** [jaroslavas/Gstreamer-Android-example#3]
Hello!

I trying to use Gstreamer on Android via Xamarin.Android(in the Visual Studio), so I built your project on the Ubuntu, took the compiled `libtutorial-5.so` and `libgstreamer_android.so` libraries and added them into the Xamarin.Android project as `AndroidNativeLibrary`'s. When I try to use `libgstreamer_android.so` using `DllImport`, then all going ok, but when I try to use `libtutorial-5.so` (of course using `DllImport`), then I get:

> DllImport unable to load library 'dlopen failed: could not load library "build/obj/local/armeabi-v7a/libgstreamer_android.so" needed by "libtutorial-5.so"; caused by library "build/obj/local/armeabi-v7a/libgstreamer_android.so" not found'.

I understand, this error occurs because `libtutorial-5.so` depends on the `libgstreamer_android.so`, and `libtutorial-5.so` trying to find `libgstreamer_android.so` library in `build/obj/local/armeabi-v7a/libgstreamer_android.so` location. 

But of course these two libraries are located in the `lib/armeabi-v7a` directory and even if I replace all two libraries or just `libgstreamer_android.so` in this location, then I still have this error. So I think I have two options:

•How can I replace library in the real build/obj/local/armeabi-v7a directory(because if I use this location in the Solution Explorer then I still have this issue)?

OR

•How can I change path of the library on which my first library will depend in the Android Studio or just in the .mk files(on the .so building stage)? 

Regards!

**Comment by jaroslavas** [comment]
Sorry, I can't help you with this issue.

**Comment by konstantin-doncov** [comment]
Ok, anyway thanks.
