### ISSUE TITLE
ndk-build .o incompatible target

### ISSUE THREAD

**Issue by MattBearson** [jaroslavas/Gstreamer-Android-example#4]
Hi, when I try to build this project - have a lot of errors:
`Error:error: C:/gstreamer/lib/gio/modules/static/libgiognutls.a(gtlsbackend-gnutls.o): incompatible target`
and after:

```
Error:Execution failed for task ':app:ndkBuild'.
> Process 'command 'C:\Android\sdk\ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2
```

But i use Windows to do it. Is it possible?
And how I can fix this errors?
Thank you

**Comment by MattBearson** [comment]
Sorry for question. Fix it:
change in Application.mk:
`APP_ABI := x86`
and use r9d NDK.
With last version didn`t work(

**Comment by jaroslavas** [comment]
Thanks for reporting how you fixed it! Maybe that'll help someone.

**Comment by lancevalour** [comment]
Hi Matt,

I have the same error:

```
Error:Execution failed for task ':app:ndkBuild'.
> A problem occurred starting process 'command 'C:\Users\ZhangY\android-sdk\ndk-bundle/ndk-build''
```

Can you tell me how to resolve this? Thanks.

Yicheng

**Comment by jaroslavas** [comment]
> change in Application.mk:
> APP_ABI := x86
> and use r9d NDK.

**Comment by lancevalour** [comment]
Same error.
Can you please post your Android.mk, build.gradle and local.properties?

**Comment by MattBearson** [comment]
error 
`:app:ndkBuild
`
but what write upper in console?
also errors with:
`incompatible target`
can you show all stacktrace of errors?

**Comment by lancevalour** [comment]
```
Information:Gradle tasks [:app:assembleDebug]
WARNING [Project: :app] Current NDK support is deprecated.  Alternative will be provided in the future.
C:\Users\ZhangY\AndroidStudioProjects\Gstreamer-Android-example\app\build/libs
C:\Users\ZhangY\android-ndk\android-ndk-r9
:app:preBuild
:app:compileDebugNdk UP-TO-DATE
:app:preDebugBuild
:app:checkDebugManifest
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:ndkBuild FAILED
Error:Execution failed for task ':app:ndkBuild'.
> A problem occurred starting process 'command 'C:\Users\ZhangY\android-ndk\android-ndk-r9/ndk-build''
Information:BUILD FAILED
Information:Total time: 2.165 secs
Information:1 error
Information:0 warnings
Information:See complete output in console
```

**Comment by rvinoth83** [comment]
Hi,

Trying to build this project in Android Studio 2.2.3. Facing this build error, please help me out

Error:Execution failed for task ':app:ndkBuild'.
> A problem occurred starting process 'command 'C:\Users\vrajendran\AppData\Local\Android\Sdk\ndk-bundle
dk-build''

Regards
Vinoth
